default_install_hook_types:
  - pre-commit
  - commit-msg

repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.11.12
  hooks:
    # Run the linter.
    - id: ruff-check
      args: [--fix]
    # Run the formatter.
    - id: ruff-format
- repo: local
  hooks:
    - id: ty
      name: ty check
      entry: uvx ty check . --ignore unresolved-import
      language: python

- repo: https://github.com/compilerla/conventional-pre-commit
  rev: v4.2.0
  hooks:
    - id: conventional-pre-commit
      stages: [commit-msg]
      args: [--verbose]

- repo: https://github.com/econchick/interrogate
  rev: 1.7.0  # or master if you're bold
  hooks:
    - id: interrogate
      args: [--quiet, --fail-under=95]
      pass_filenames: false  # needed if excluding files with pyproject.toml or setup.cfg

